### ISSUE TITLE
Candidates were viewed by Client email notification is not received when the resume of the user is downloaded(1st time)

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#506]
**Steps**
Log in from a project member
Download the resume of the user in Review status

Should send the email notification to the member, but it is not sent

Team: https://platform.topcoder-dev.com/taas/myteams/18361/positions/17a74bde-a156-4c66-8fcf-557e2c8e19e1/candidates/to-review

**Comment by maxceem** [comment]
Would be fixed by https://github.com/topcoder-platform/taas-app/issues/492

**Comment by maxceem** [comment]
This issue has been fixed by https://github.com/topcoder-platform/taas-app/issues/492 and it works.

We are going to come with a technically better solution during cool down period which would be tracked here https://github.com/topcoder-platform/taas-app/issues/495

**Comment by sdgun** [comment]
@maxceem To test this I created a new position and downloaded the resume, but I don't see any emails being sent to the member.

This is what I used for testing.
https://platform.topcoder-dev.com/taas/myteams/18388/positions/95d44a8b-babc-468f-b804-3f418c433270/candidates/to-review

**Comment by maxceem** [comment]
@sdgun which user did you use to download the resume? Just in case we have to use a user without any Topcoder roles with only one general role `Topcoder User`. If you let me know the user I may check the user roles for you.

**Comment by sdgun** [comment]
@maxceem I tried with 
taasintake6, taasintake5 and taasintake8

**Comment by maxceem** [comment]
@sdgun there appeared to be some issue. It's fixed now on DEV.

To verify you would have to create a new Job Candidate, as this one was already marked as viewed.

**Comment by sdgun** [comment]
@maxceem Still doesn't work in dev, I checked by creating a new position https://platform.topcoder-dev.com/taas/myteams/18591/positions/be7ae556-65ee-4907-8a4a-12fe68f1d226/candidates/to-review, can this only be an issue in dev?

**Comment by sdgun** [comment]
Thanks @maxceem Checked with taasintake5 and received this email

![image](https://user-images.githubusercontent.com/4592712/131283514-7b164086-a963-4970-a86a-27b7f561a5e1.png)
